Volume conecte_me_postgres_data  Removing
Volume conecte_me_postgres_data  Removed
.
├── __init__.py
├── migrations
│   ├── 0001_initial.py
│   ├── 0002_user42_email_address_user42_first_name_and_more.py
│   ├── 0003_user42_is_2fa_enabled_user42_totp_secret.py
│   ├── 0004_alter_user42_totp_secret.py
│   ├── __init__.py
│   └── __pycache__
│       ├── 0001_initial.cpython-310.pyc
│       ├── 0002_user42_email_address_user42_first_name_and_more.cpython-310.pyc
│       ├── 0003_user42_is_2fa_enabled_user42_totp_secret.cpython-310.pyc
│       ├── 0004_alter_user42_totp_secret.cpython-310.pyc
│       └── __init__.cpython-310.pyc
├── models.py
├── output.log
├── __pycache__
│   ├── __init__.cpython-310.pyc
│   ├── models.cpython-310.pyc
│   ├── tests.cpython-310.pyc
│   ├── twofa_views.cpython-310.pyc
│   ├── urls.cpython-310.pyc
│   ├── utils.cpython-310.pyc
│   └── views.cpython-310.pyc
├── templates
│   └── 2fa_setup.html
├── tests.py
├── twofa_views.py
├── urls.py
├── utils.py
└── views.py

4 directories, 26 files
cat: nginx.conf: No such file or directory
cat: .env: No such file or directory
